services:
  localstack:
    image: localstack/localstack:latest
    container_name: ccnetizen
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - "./ccnetizen-data:/var/lib/ccnetizen"